### ISSUE TITLE
CircleCI 2.1 error

### ISSUE THREAD

**Issue by ilyapuchka** [sponomarev/circleci-cancel-builds#2]
Currently migrating to CircleCI 2.1 and while it allows cancelation of redundant builds out of the box it is not conditional, so we keep using this tool. But we started to see issues with jobs query:

`jq: error (at <stdin>:2): Cannot index string with string "status"`

Any idea what can be causing it?

**Comment by sponomarev** [comment]
Hey @ilyapuchka, I'm glad to hear that you're still using it.

Unfortunately, it's no compatible with CircleCI 2.1 since [they deprecated Job API](https://circleci.com/docs/2.0/api-job-trigger/#section=jobs).

**Comment by ilyapuchka** [comment]
The thing is that the endpoint to get list of jobs still works though (they may indeed remove it in the future though) and it's possible to get all the jobs.

**Comment by sponomarev** [comment]
I've just tried it  and received 

```
{
  "message" : "Project not found"
}
```

😞

**Comment by ilyapuchka** [comment]
hm, strange. I used to get this when was using a wrong token.

**Comment by ilyapuchka** [comment]
It seems like the issue was that some env variables were missing, as soon as we imported them properly it works 👍

**Comment by sponomarev** [comment]
@ilyapuchka Can you share your investigation results? What the variables was missing?

**Comment by ilyapuchka** [comment]
I guess it was just circle ci access token and the request was failing
without it of course, not that something was wrong with parsing results.
